#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>
#include <unistd.h>
using namespace std;
int generaterandnum(void){
    srand(time(0));
    return rand()%10 + 1;
}
void rules(void);
int main(){
    int Balance, Betting_amt, userguess, cpguess;
    char ch;
    string name;
    cout << endl << "---------- Welcome to Casino Number Guessing Game -------------" << endl << endl;
    sleep(1);
    rules();
    cout << "Enter your Name : "; cin >> name;
    cout << "Enter Your Balance : "; cin >> Balance;
    do{
        cout << "Enter your betting amount: ";
        cin >> Betting_amt;
        if(Betting_amt > Balance){
            cout << "-- Betting amount cannot be greater than the balance."<< endl;
            cout << "-- Enter a smaller amount." << endl;
            sleep(1);
        }
    }while(Betting_amt>Balance);
    do{
        cout << "\t\t\t Lets Start the game." << endl << endl;
        sleep(1);
        cout << "-- Computer turn: " << endl;
        cpguess = generaterandnum();
        cout << "-- Computer selected an option. Now its Your turn to guess." << endl << endl;
        sleep(1);
        do {
            cout << "-- " << name <<  " Guess any number in between 1 - 10 " << endl;
            cin >> userguess;
            if(userguess > 10 || userguess < 0){
                cout << "-- Wrong input" << endl
                << "-- Enter again." << endl;
            }
        }while (userguess > 10 || userguess < 0);
        if(userguess == cpguess){
            cout << "\t\t\t WOW CONGRATULATIONS" << endl
            << "--- You Guessed it correctly." << endl
            << "-- You won " << Betting_amt*2 << " Amount." << endl;
            Balance = Balance + (Betting_amt*2);
        }
        else {
            cout << "-- You Lost the game." << endl;
            cout << "You lost " << Betting_amt << " Amount." << endl;
            Balance -= Betting_amt;
        }
        cout << "Press Y to continue the game." << endl;
        cout << "Press any key to exit the game." << endl;
        cin >> ch;
        if((ch == 'Y' || ch == 'y') && Balance < 0){
            cout << "-- You cannot play." << endl
            << "-- Your balance is " << Balance << endl;
            break;
        }
    }while(ch == 'Y' || ch == 'y');
    cout << "-- Your Balance is : " << Balance << endl;
    cout << "\t\t\t THANKS FOR PLAYING." << endl;
    cout << "\t\t\t HAVE A GOOD DAY." << endl;
    return 0;
}
void rules(void){
    cout << "RULES: " << endl
    << "--> In this Game you have Bet some amount and guess the number which the game is generated." << endl
    << "--> If Your guess is correct as generated by the game you will get doubled of your betting money." << endl
    << "--> Otherwise your money will be deducted from your balance." << endl
    << "--> Betting money should be above $10.0" << endl << endl;
    sleep(4);
    cout << "\t\t\t ARE YOU READY " << endl; 
    sleep(2);
}